In [1]:
print("Day 1 - Data Ingestion")

Day 1 - Data Ingestion

In [2]:
import pandas as pd
import numpy as np
import requests

print("Libraries loaded successfully")

Libraries loaded successfully

In [3]:
import requests

url = "https://api.mfapi.in/mf/125497"

response = requests.get(url)

print("Status Code:", response.status_code)

data = response.json()

print(data["meta"]["scheme_name"])

Status Code: 200
SBI Small Cap Fund - Direct Plan - Growth

In [4]:
import pandas as pd

nav_df = pd.DataFrame(data["data"])

nav_df.head()

         date        nav
0  19-06-2026  202.07610
1  18-06-2026  200.95650
2  17-06-2026  199.83020
3  16-06-2026  198.61520
4  15-06-2026  198.03200

In [5]:
nav_df.to_csv("../data/raw/nav_125497.csv", index=False)

print("NAV data saved successfully")

OSError: Cannot save file into a non-existent directory: '..\data\raw'

In [6]:
import os

print(os.getcwd())

C:\Users\tdj61\MutualFundAnalytics

In [7]:
os.listdir()

['.ipynb_checkpoints',
 'dashboard',
 'data',
 'day1_data_ingestion.ipynb',
 'notebooks',
 'reports',
 'requirements.txt',
 'sql']

In [8]:
nav_df.to_csv("nav_125497.csv", index=False)

print("NAV data saved successfully")

NAV data saved successfully

In [9]:
import os

os.makedirs("data/raw", exist_ok=True)

nav_df.to_csv("data/raw/nav_125497.csv", index=False)

print("Saved in data/raw folder")

Saved in data/raw folder

In [10]:
os.listdir("data/raw")

['nav_125497.csv']

In [11]:
print("Shape:", nav_df.shape)

print("\nData Types:")
print(nav_df.dtypes)

print("\nFirst 5 Rows:")
print(nav_df.head())

Shape: (3105, 2)

Data Types:
date    str
nav     str
dtype: object

First 5 Rows:
         date        nav
0  19-06-2026  202.07610
1  18-06-2026  200.95650
2  17-06-2026  199.83020
3  16-06-2026  198.61520
4  15-06-2026  198.03200

In [12]:
print("\nMissing Values:")
print(nav_df.isnull().sum())

Missing Values:
date    0
nav     0
dtype: int64

In [13]:
with open("reports/data_quality_summary.txt", "w") as f:
    f.write(f"Rows, Columns: {nav_df.shape}\n")
    f.write("\nData Types:\n")
    f.write(str(nav_df.dtypes))
    f.write("\n\nMissing Values:\n")
    f.write(str(nav_df.isnull().sum()))

print("Data Quality Summary Saved")

Data Quality Summary Saved

In [14]:
import os

print("Raw files:", os.listdir("data/raw"))
print("Reports:", os.listdir("reports"))

Raw files: ['nav_125497.csv']
Reports: ['data_quality_summary.txt']

In [15]:
import pandas as pd
import os

files = os.listdir("data/raw")
print(files)

['nav_125497.csv']

In [16]:
import pandas as pd
import os

for file in os.listdir("data/raw"):
    if file.endswith(".csv"):
        df = pd.read_csv(f"data/raw/{file}")

        print("\n" + "="*50)
        print("File:", file)
        print("Shape:", df.shape)
        print(df.dtypes)
        print(df.head())

==================================================
File: nav_125497.csv
Shape: (3105, 2)
date        str
nav     float64
dtype: object
         date       nav
0  19-06-2026  202.0761
1  18-06-2026  200.9565
2  17-06-2026  199.8302
3  16-06-2026  198.6152
4  15-06-2026  198.0320

In [17]:
import pandas as pd
import os

files = os.listdir("data/raw")

for file in files:
    df = pd.read_csv(f"data/raw/{file}")
    print("\n" + "="*50)
    print(file)
    print("Shape:", df.shape)
    print(df.dtypes)
    print(df.head())

PermissionError: [Errno 13] Permission denied: 'data/raw/.ipynb_checkpoints'

In [18]:
import pandas as pd
import os

files = [f for f in os.listdir("data/raw") if f.endswith(".csv")]

for file in files:
    df = pd.read_csv(f"data/raw/{file}")

    print("\n" + "="*50)
    print(file)
    print("Shape:", df.shape)
    print(df.head())

==================================================
01_fund_master.csv
Shape: (40, 15)
   amfi_code       fund_house                                   scheme_name  \
0     119551  SBI Mutual Fund     SBI Bluechip Fund - Regular Plan - Growth
1     119552  SBI Mutual Fund      SBI Bluechip Fund - Direct Plan - Growth
2     119598  SBI Mutual Fund    SBI Small Cap Fund - Regular Plan - Growth
3     119599  SBI Mutual Fund     SBI Small Cap Fund - Direct Plan - Growth
4     119120  SBI Mutual Fund  SBI Magnum Gilt Fund - Regular Plan - Growth

  category sub_category     plan launch_date                  benchmark  \
0   Equity    Large Cap  Regular  2006-02-14              NIFTY 100 TRI
1   Equity    Large Cap   Direct  2013-01-01              NIFTY 100 TRI
2   Equity    Small Cap  Regular  2009-09-09       BSE 250 SmallCap TRI
3   Equity    Small Cap   Direct  2013-01-01       BSE 250 SmallCap TRI
4     Debt         Gilt  Regular  2000-12-30  CRISIL Dynamic Gilt Index

   expense_ratio_pct  exit_load_pct  min_sip_amount  min_lumpsum_amount  \
0               1.54            1.0             500                1000
1               0.66            1.0             500                1000
2               1.43            1.0             500                1000
3               0.72            1.0             500                1000
4               0.77            0.0             500                1000

    fund_manager risk_category sebi_category_code
0  Sohini Andani      Moderate               EC01
1  Sohini Andani      Moderate               EC01
2  R. Srinivasan     Very High               EC03
3  R. Srinivasan     Very High               EC03
4   Dinesh Ahuja           Low               DC02

==================================================
02_nav_history.csv
Shape: (46000, 3)
   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

==================================================
03_aum_by_fund_house.csv
Shape: (90, 5)
         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

==================================================
04_monthly_sip_inflows.csv
Shape: (48, 6)
     month  sip_inflow_crore  active_sip_accounts_crore  \
0  2022-01             11517                       4.91
1  2022-02             11438                       4.93
2  2022-03             12328                       5.09
3  2022-04             11863                       5.48
4  2022-05             12286                       5.55

   new_sip_accounts_lakh  sip_aum_lakh_crore  yoy_growth_pct
0                   9.10                4.80             NaN
1                   8.20                4.85             NaN
2                  10.50                5.01             NaN
3                   9.52                5.12             NaN
4                   8.10                5.15             NaN

==================================================
05_category_inflows.csv
Shape: (144, 3)
     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

==================================================
06_industry_folio_count.csv
Shape: (21, 6)
     month  total_folios_crore  equity_folios_crore  debt_folios_crore  \
0  2022-01               13.26                 9.28               1.86
1  2022-04               13.91                 9.74               1.95
2  2022-07               13.85                 9.69               1.94
3  2022-10               14.12                 9.88               1.98
4  2023-01               14.81                10.37               2.07

   hybrid_folios_crore  others_folios_crore
0                 0.80                 1.33
1                 0.83                 1.39
2                 0.83                 1.38
3                 0.85                 1.41
4                 0.89                 1.48

==================================================
07_scheme_performance.csv
Shape: (40, 19)
   amfi_code                                   scheme_name       fund_house  \
0     119551     SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund
1     119552      SBI Bluechip Fund - Direct Plan - Growth  SBI Mutual Fund
2     119598    SBI Small Cap Fund - Regular Plan - Growth  SBI Mutual Fund
3     119599     SBI Small Cap Fund - Direct Plan - Growth  SBI Mutual Fund
4     119120  SBI Magnum Gilt Fund - Regular Plan - Growth  SBI Mutual Fund

    category     plan  return_1yr_pct  return_3yr_pct  return_5yr_pct  \
0  Large Cap  Regular           12.42           12.36           14.45
1  Large Cap   Direct           15.25           11.30           14.23
2  Small Cap  Regular           24.56           23.39           20.67
3  Small Cap   Direct           20.59           23.14           21.82
4       Gilt  Regular            5.34            6.07            5.43

   benchmark_3yr_pct  alpha  beta  sharpe_ratio  sortino_ratio  \
0              11.49   0.87  0.89          0.88           1.29
1               9.52   1.78  0.87          0.81           1.29
2              22.16   1.23  0.89          0.94           1.35
3              22.01   1.13  1.04          0.93           1.67
4               4.47   1.60  0.22          1.52           2.11

   std_dev_ann_pct  max_drawdown_pct  aum_crore  expense_ratio_pct  \
0             14.0            -21.70      14288               1.54
1             14.0            -24.43       1231               0.66
2             25.0            -13.35      19259               1.43
3             25.0            -24.78      36061               0.72
4              4.0             -2.30      24101               0.77

   morningstar_rating risk_grade
0                   4   Moderate
1                   3   Moderate
2                   5  Very High
3                   4  Very High
4                   5        Low

==================================================
08_investor_transactions.csv
Shape: (32778, 13)
  investor_id transaction_date  amfi_code transaction_type  amount_inr  \
0   INV003054       2024-01-01     119092              SIP        1834
1   INV002952       2024-01-01     148567       Redemption      392882
2   INV003420       2024-01-01     118636              SIP         912
3   INV003436       2024-01-01     118634              SIP        1102
4   INV004691       2024-01-01     119094          Lumpsum        8682

         state       city city_tier age_group  gender  annual_income_lakh  \
0    Telangana  Hyderabad       T30       56+  Female                77.1
1       Punjab   Amritsar       B30     18-25    Male                 7.1
2      Haryana  Faridabad       B30     36-45    Male                47.2
3  Maharashtra     Mumbai       T30     36-45  Female                54.4
4        Delhi      Noida       T30     26-35    Male                14.5

  payment_mode kyc_status
0          UPI   Verified
1       Cheque   Verified
2      Mandate   Verified
3       Cheque    Pending
4  Net Banking    Pending

==================================================
09_portfolio_holdings.csv
Shape: (322, 8)
   amfi_code stock_symbol                stock_name       sector  weight_pct  \
0     119551    POWERGRID    Power Grid Corporation    Utilities       13.85
1     119551     HDFCBANK             HDFC Bank Ltd      Banking       11.19
2     119551       GRASIM     Grasim Industries Ltd  Diversified        9.90
3     119551      DRREDDY  Dr. Reddy's Laboratories       Pharma        4.76
4     119551   ASIANPAINT          Asian Paints Ltd       Paints       10.25

   market_value_cr  current_price_inr portfolio_date
0           737.09            6011.08     2025-12-31
1            88.97            1074.65     2025-12-31
2           208.45            5964.59     2025-12-31
3           161.32            3748.82     2025-12-31
4           725.90            1321.45     2025-12-31

==================================================
10_benchmark_indices.csv
Shape: (8050, 3)
         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [19]:
import pandas as pd
import os

summary = []

files = [f for f in os.listdir("data/raw") if f.endswith(".csv")]

for file in files:
    df = pd.read_csv(f"data/raw/{file}")

    summary.append({
        "File": file,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": df.isnull().sum().sum()
    })

summary_df = pd.DataFrame(summary)
summary_df

                           File   Rows  Columns  Missing Values
0            01_fund_master.csv     40       15               0
1            02_nav_history.csv  46000        3               0
2      03_aum_by_fund_house.csv     90        5               0
3    04_monthly_sip_inflows.csv     48        6              12
4       05_category_inflows.csv    144        3               0
5   06_industry_folio_count.csv     21        6               0
6     07_scheme_performance.csv     40       19               0
7  08_investor_transactions.csv  32778       13               0
8     09_portfolio_holdings.csv    322        8               0
9      10_benchmark_indices.csv   8050        3               0

In [20]:
fund_master = pd.read_csv("data/raw/01_fund_master.csv")

print(fund_master["fund_house"].unique())
print(fund_master["category"].unique())
print(fund_master["sub_category"].unique())

<StringArray>
[         'SBI Mutual Fund',         'HDFC Mutual Fund',
      'ICICI Prudential MF',          'Nippon India MF',
        'Kotak Mahindra MF',         'Axis Mutual Fund',
 'Aditya Birla Sun Life MF',          'UTI Mutual Fund',
           'Mirae Asset MF',          'DSP Mutual Fund']
Length: 10, dtype: str
<StringArray>
['Equity', 'Debt']
Length: 2, dtype: str
<StringArray>
[      'Large Cap',       'Small Cap',            'Gilt',         'Mid Cap',
  'Short Duration',           'Value',          'Liquid',       'Index/ETF',
       'Flexi Cap',           'Index', 'Large & Mid Cap',            'ELSS']
Length: 12, dtype: str

In [21]:
fund_master = pd.read_csv("data/raw/01_fund_master.csv")
nav_history = pd.read_csv("data/raw/02_nav_history.csv")

fund_codes = set(fund_master["amfi_code"])
nav_codes = set(nav_history["amfi_code"])

missing_codes = fund_codes - nav_codes

print("Fund Master Codes:", len(fund_codes))
print("NAV History Codes:", len(nav_codes))
print("Missing Codes:", len(missing_codes))

if len(missing_codes) == 0:
    print("✅ All AMFI codes validated successfully")
else:
    print("❌ Missing Codes:")
    print(missing_codes)

Fund Master Codes: 40
NAV History Codes: 40
Missing Codes: 0
✅ All AMFI codes validated successfully

In [22]:
scheme_codes = [119551, 120503, 118632, 119092, 120841]

In [23]:
scheme_codes = [119551, 120503, 118632, 119092, 120841]

for code in scheme_codes:
    url = f"https://api.mfapi.in/mf/{code}"

    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()

        df = pd.DataFrame(data["data"])

        df.to_csv(f"data/raw/nav_{code}.csv", index=False)

        print(f"Saved NAV for {code}")
    else:
        print(f"Failed for {code}")

Saved NAV for 119551
Saved NAV for 120503
Saved NAV for 118632
Saved NAV for 119092
Saved NAV for 120841

In [24]:
import os
os.listdir("data/raw")

['.ipynb_checkpoints',
 '01_fund_master.csv',
 '02_nav_history.csv',
 '03_aum_by_fund_house.csv',
 '04_monthly_sip_inflows.csv',
 '05_category_inflows.csv',
 '06_industry_folio_count.csv',
 '07_scheme_performance.csv',
 '08_investor_transactions.csv',
 '09_portfolio_holdings.csv',
 '10_benchmark_indices.csv',
 'nav_118632.csv',
 'nav_119092.csv',
 'nav_119551.csv',
 'nav_120503.csv',
 'nav_120841.csv']

In [25]:
import os
print(os.listdir("data/raw"))

['.ipynb_checkpoints', '01_fund_master.csv', '02_nav_history.csv', '03_aum_by_fund_house.csv', '04_monthly_sip_inflows.csv', '05_category_inflows.csv', '06_industry_folio_count.csv', '07_scheme_performance.csv', '08_investor_transactions.csv', '09_portfolio_holdings.csv', '10_benchmark_indices.csv', 'nav_118632.csv', 'nav_119092.csv', 'nav_119551.csv', 'nav_120503.csv', 'nav_120841.csv']

In [26]:
summary_df

                           File   Rows  Columns  Missing Values
0            01_fund_master.csv     40       15               0
1            02_nav_history.csv  46000        3               0
2      03_aum_by_fund_house.csv     90        5               0
3    04_monthly_sip_inflows.csv     48        6              12
4       05_category_inflows.csv    144        3               0
5   06_industry_folio_count.csv     21        6               0
6     07_scheme_performance.csv     40       19               0
7  08_investor_transactions.csv  32778       13               0
8     09_portfolio_holdings.csv    322        8               0
9      10_benchmark_indices.csv   8050        3               0

In [27]:
summary_df.to_csv("reports/final_data_summary.csv", index=False)
print("Summary saved")

Summary saved

In [28]:
fund_master = pd.read_csv("data/raw/01_fund_master.csv")
nav_history = pd.read_csv("data/raw/02_nav_history.csv")

fund_codes = set(fund_master["amfi_code"])
nav_codes = set(nav_history["amfi_code"])

missing_codes = fund_codes - nav_codes

print("Missing Codes:", len(missing_codes))

Missing Codes: 0

In [29]:
scheme_codes = [119551, 120503, 118632, 119092, 120841]

for code in scheme_codes:
    url = f"https://api.mfapi.in/mf/{code}"
    data = requests.get(url).json()

    df = pd.DataFrame(data["data"])
    df.to_csv(f"data/raw/nav_{code}.csv", index=False)

    print(f"Saved NAV for {code}")

Saved NAV for 119551
Saved NAV for 120503
Saved NAV for 118632
Saved NAV for 119092
Saved NAV for 120841

In [30]:
import os
print(os.listdir("data/raw"))

['.ipynb_checkpoints', '01_fund_master.csv', '02_nav_history.csv', '03_aum_by_fund_house.csv', '04_monthly_sip_inflows.csv', '05_category_inflows.csv', '06_industry_folio_count.csv', '07_scheme_performance.csv', '08_investor_transactions.csv', '09_portfolio_holdings.csv', '10_benchmark_indices.csv', 'nav_118632.csv', 'nav_119092.csv', 'nav_119551.csv', 'nav_120503.csv', 'nav_120841.csv']